# Generated by Django 3.2.6 on 2021-08-29 05:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('image_labelling', '0004_alter_label_unique_together'),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='label',
            name='image_label_id_7335e5_idx',
        ),
        migrations.AddIndex(
            model_name='label',
            index=models.Index(fields=['id', 'user_id', 'image_id', 'label'], name='image_label_id_e50f3b_idx'),
        ),
    ]
